- name: "Generate kube-scheduler certificates"
  import_role:
    name: utils/ca
  vars:
    ca_certs:
      - {name: "kube-scheduler", cn: "system:kube-scheduler", o: "system:kube-scheduler"}

- name: "Create /var/lib/kubernetes directory"
  file:
    path: /var/lib/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0700
  become: true
