- name: "Download previously generated files"
  fetch:
    src: "/var/lib/kubernetes/{{ item }}"
    dest: "{{ workdir }}/{{ item }}"
    fail_on_missing: false
    flat: true
  loop: "{{ master_files }}"
  delegate_to: "{{ groups['master'] | first }}"
  run_once: true
  become: true

- import_tasks: "{{ role_path }}/tasks/04-certificate_authority.yml"
- import_tasks: "{{ role_path }}/tasks/05-kubernetes_configuration_files.yml"
- import_tasks: "{{ role_path }}/tasks/06-data_encryption_config.yml"
- import_tasks: "{{ role_path }}/tasks/08-bootstrapping_kubernetes_controllers.yml"
