- name: "Generate kube-controller-manager certificates"
  import_role:
    name: utils/ca
  vars:
    ca_certs:
      - {name: "kube-controller-manager", cn: "system:kube-controller-manager", o: "system:kube-controller-manager"}

- name: "Create /var/lib/kubernetes directory"
  file:
    path: /var/lib/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0700
  become: true
