cfssl_base_url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/{{ hostvars['localhost']['ansible_system'] | lower }}

ca_rsa_keysize: 2048
ca_ca_expiry: "8760h"
ca_cert_expiry: "8760h"

ca_cn: Kubernetes
ca_country: HU
ca_locality: Budapest
ca_organization: Kubernetes
ca_organizational_unit: "Kubernetes The Hard Way"
ca_state: Pest
